### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pieterhouwen** [SpiderLabs/portia#3]
When running the tool against my own Windows machine I get the following error:

Traceback (most recent call last):
  File "portia.py", line 4626, in <module>
    mountSysvol(username,password)
  File "portia.py", line 3382, in mountSysvol
    status,foundAdmin=testDomainCredentials(username,password,None,dcList[0],'WORKGROUP',True)
IndexError: list index out of range

Am I missing a dependency or something?

**Comment by milo2012** [comment]
Hi, 
Thank you for reporting the issue. Please do a git pull. 
The latest commit fixes the issue https://github.com/SpiderLabs/portia/commit/f9fd86c633be0f79fe640e79dc852117d0b0d7ff

**Comment by pieterhouwen** [comment]
Thanks for your comment, that fixed the Out of range error, but now it doesn't detect the system anymore:

'
root@supersecretkali:/opt/pentest/portia# python portia.py -d ******** -u ****** -p ****** 192.168.39.147
[*] Scanning Target Network
[+] No Domain Controllers/NetBIOS/RDP ports detected on target hosts

root@supersecretkali:/opt/pentest/portia# nmap 192.168.39.147

Starting Nmap 7.50 ( https://nmap.org ) at 2017-08-09 08:16 EDT
Nmap scan report for 192.168.39.147
Host is up (0.00027s latency).
Not shown: 994 filtered ports
PORT     STATE SERVICE
135/tcp  open  msrpc
139/tcp  open  netbios-ssn
445/tcp  open  microsoft-ds
2869/tcp open  icslap
3389/tcp open  ms-wbt-server
5357/tcp open  wsdapi
MAC Address: ************** (Asustek Computer)

Nmap done: 1 IP address (1 host up) scanned in 20.03 seconds
root@supersecretkali:/opt/pentest/portia#

**Comment by boupjof** [comment]
Same error for me

**Comment by pieterhouwen** [comment]
The index error has returned.

root@supersecretkali:/opt/pentest/portia/.git# cat FETCH_HEAD 
f9fd86c633be0f79fe640e79dc852117d0b0d7ff		branch 'master' of https://github.com/spiderlabs/portia

**Comment by ITmustang** [comment]
i updated but now get this when i run it 

root@kali:/opt/portia# ./portia.py (ip subnet) -d **** -u ***** -p ***** -M shares
./portia.py: line 7: syntax error near unexpected token `newline'                         
./portia.py: line 7: `<!DOCTYPE html>'
