### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by bucky67gto** [SpiderLabs/portia#7]
Looks very useful.  After installing I unfortunately am receiving the following:

Traceback (most recent call last):
  File "portia.py", line 9, in <module>
    from deps.secretsdump import *
  File "/root/portia/deps/secretsdump.py", line 56, in <module>
    from impacket.examples.secretsdump import LocalOperations, RemoteOperations, SAMHashes, LSASecrets, NTDSHashes
ImportError: No module named secretsdump

any thoughts? Thanks

**Comment by SecureThisShit** [comment]
I fixed this one by replacing secretsdump.py with the actual impacket one:

https://github.com/CoreSecurity/impacket/blob/master/examples/secretsdump.py

But than i get another new error:

from impacket.krb5.pac import PKERB_VALIDATION_INFO, KERB_VALIDATION_INFO, KERB_SID_AND_ATTRIBUTES, PAC_CLIENT_INFO, \
ImportError: No module named pac

Reinstall impacket doesnt help.

**Comment by SecureThisShit** [comment]
I just found the Solution for me.

Try to run python -->
from impacket import version
version

My impacket Module files were in the /home/.local/lib/python2.7/site-packages/impacket directory. I Just updated all those files with the newest Impacket files, now it works.
